import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    // The real build dir behind the .next symlink (kept out of iCloud sync).
    ".next.nosync/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated Prisma client — machine-written, regenerated by `prisma generate`.
    "src/generated/**",
  ]),
]);

export default eslintConfig;
