import { NextRequest, NextResponse } from "next/server";
import { LOCAL_USER_ID, findOwnedDocument } from "@/lib/db";
import { imagePathFor, readStoredFile, sniffImageType } from "@/lib/storage";

export const runtime = "nodejs";

// Asset names are generated by extraction as "{blockIndex}-{sha8}.{ext}" —
// anything else (including any traversal attempt) is rejected outright.
const ASSET_NAME = /^\d+-[a-f0-9]{8}\.(jpg|png|gif|webp)$/;

// Serve one of a document's inline images (EPUB figures). The content hash in
// the filename makes the URL change whenever the bytes do, so the immutable
// cache can never serve a stale asset across re-extraction.
export async function GET(
  _req: NextRequest,
  { params }: { params: Promise<{ id: string; asset: string }> }
) {
  const { id, asset } = await params;
  if (!ASSET_NAME.test(asset)) {
    return NextResponse.json({ error: "Not found." }, { status: 404 });
  }
  const doc = await findOwnedDocument(id, { select: { id: true } });
  if (!doc) {
    return NextResponse.json({ error: "Not found." }, { status: 404 });
  }
  try {
    const data = await readStoredFile(imagePathFor(LOCAL_USER_ID, id, asset));
    return new NextResponse(new Uint8Array(data), {
      headers: {
        "Content-Type": sniffImageType(data),
        "Cache-Control": "public, max-age=31536000, immutable",
      },
    });
  } catch {
    return NextResponse.json({ error: "Image missing." }, { status: 404 });
  }
}
